Added other parameters as launchfile args + framerate check
transcendrobotics/zed_cpu_ros pull request #10
Opened 2018-04-04 15:13 UTC by virgileTN

Hello, I'm not sure why, but previous changes already merged into your master Also appears here :/. 

Simple args adding, with few checks on inputs values : 
- ff5de5b  show_image
- f6b2db2 resolution + default is resolution >3
- 3a5529c framerate, Also added a warning in case of downgraded framerate due to too high frequency for selected resolution (not changing the behaviour, but I think it's always good to let user know when everything is not running as asked). 

Best regards,

2018-04-07 18:21 UTC, willdzeng requested changes
Just a few comments, thanks.

2018-04-07 18:21 UTC, willdzeng commented on src/zed_cpu_ros.cpp
> +			ROS_WARN("frame_rate(%fHz) to high for resolution(%s), downgraded to %fHz",frame_rate,reso_str.c_str(),max_frame_rate);
to -> too

2018-04-07 18:21 UTC, willdzeng commented on src/zed_cpu_ros.cpp
> + 			case 3: max_frame_rate = 100; reso_str = "VGA"; break;
default:
ROS_FATAL("Unknow resolution passed");
return;

2018-04-10 06:39 UTC, virgileTN commented
fixed in 85b416f :)

2018-04-10 15:10 UTC, virgileTN commented
5bc4aee added support for encoding selection. It was useful for [Kalibr](https://github.com/ethz-asl/kalibr) which is not working with brg8 encoding.

2018-04-10 15:49 UTC, willdzeng requested changes

2018-04-10 15:49 UTC, willdzeng commented on src/zed_cpu_ros.cpp
> +		cv_image.encoding = encoding;
cv_image.encoding = encoding_;

2018-04-10 15:49 UTC, willdzeng commented on src/zed_cpu_ros.cpp
> +	void publishImage(cv::Mat img, image_transport::Publisher &img_pub, std::string img_frame_id, ros::Time t, const std::string& encoding) {
Can you try change the input to const cv::Mat& img?
And test if it works with a subscriber.

2018-04-10 15:49 UTC, willdzeng commented on src/zed_cpu_ros.cpp
> +	void publishImage(cv::Mat img, image_transport::Publisher &img_pub, std::string img_frame_id, ros::Time t, const std::string& encoding) {
Also const std::string& img_frame_id

2018-04-16 04:03 UTC, willdzeng approved these changes

2018-04-16 04:03 UTC, merged

2018-04-16 04:03 UTC, willdzeng commented
I am going to address the comments myself.
Thanks for your contribution.

2018-04-16 05:03 UTC, willdzeng commented on src/zed_cpu_ros.cpp
> +		cv_image.encoding = encoding;
Does this even work? I tried on my machine changing encoding to rgb8, the color are wrong, looks like we need to do a conversion on the cv mat itself, the image encoding from the output of zed is always bgr8.